---
- name: The great OpenStack
  hosts: all
  vars:
    - mysql_root_password: password
    - rabbit_openstack_password: password
    - admin_password: password
    - demo_password: password
    - keystone_password: password
    - glance_password: password
    - nova_password: password
    - neutron_password: password
    - metadata_proxy_shared_secret: secret
    - external_interface: eth1
  roles:
    - role: geerlingguy.mysql
      become: yes
    - role: openstack
