---
- name: The great OpenStack
  hosts: all
  vars:
    all_in_one: True
    nodes:
      controller:
        management_interface: "{{ ansible_default_ipv4.interface }}"
        management_ip_address: "{{ ansible_default_ipv4.address }}"
      network:
        management_interface: "{{ ansible_default_ipv4.interface }}"
        management_ip_address: "{{ ansible_default_ipv4.address }}"
        external_interface: eth1
      compute:
        management_interface: "{{ ansible_default_ipv4.interface }}"
        management_ip_address: "{{ ansible_default_ipv4.address }}"
    networking:
      management:
        network: "{{ '{}/{}'.format(ansible_default_ipv4.network, ansible_default_ipv4.netmask) | ipaddr('net') }}"
      external:
        network: '192.168.33.0/24'
        allocation_pool:
          start: '192.168.33.241'
          start: '192.168.33.250'
        gateway: '192.168.33.1'
  roles:
    - role: geerlingguy.mysql
      become: yes
      mysql_root_password: password
    - role: openstack
  tasks:
    - name: Create the external network
      command: >
        neutron \
          --os-auth-url http://controller:35357/v3 \
          --os-project-domain-id default --os-user-domain-id default \
          --os-project-name admin \
          --os-username admin --os-password {{ admin_password }} \
          net-create ext-net \
            --router:external \
            --provider:physical_network external \
            --provider:network_type flat
      ignore_errors: yes
    - name: Create the external subnet
      command: >
        neutron \
          --os-auth-url http://controller:35357/v3 \
          --os-project-domain-id default --os-user-domain-id default \
          --os-project-name admin \
          --os-username admin --os-password {{ admin_password }} \
          subnet-create ext-net {{ networking.external.network }} \
            --name ext-subnet \
            --allocation-pool start={{ networking.external.allocation_pool.start }},end={{ networking.external.allocation_pool.end }} \
            --disable-dhcp \
            --gateway {{ networking.external.gateway }}
      ignore_errors: yes
    - name: List all the tenant networks
      command: >
        neutron \
          --os-auth-url http://controller:35357/v3 \
          --os-project-domain-id default --os-user-domain-id default \
          --os-project-name demo \
          --os-username demo --os-password {{ demo_password }} \
          net-list
      register: net_list
    - name: Create the tenant network
      command: >
        neutron \
          --os-auth-url http://controller:35357/v3 \
          --os-project-domain-id default --os-user-domain-id default \
          --os-project-name demo \
          --os-username demo --os-password {{ demo_password }} \
          net-create demo-net
      when: net_list.stdout.find('demo-net') == -1
    - name: Create the tenant subnet
      command: >
        neutron \
          --os-auth-url http://controller:35357/v3 \
          --os-project-domain-id default --os-user-domain-id default \
          --os-project-name demo \
          --os-username demo --os-password {{ demo_password }} \
          subnet-create demo-net 172.16.1.0/24 \
          --name demo-subnet \
          --dns-nameserver 8.8.8.8 \
          --gateway 172.16.1.1
      ignore_errors: yes
    - name: List all routers
      command: >
        neutron \
          --os-auth-url http://controller:35357/v3 \
          --os-project-domain-id default --os-user-domain-id default \
          --os-project-name demo \
          --os-username demo --os-password {{ demo_password }} \
          router-list
      register: router_list
    - name: Create the router
      command: >
        neutron \
          --os-auth-url http://controller:35357/v3 \
          --os-project-domain-id default --os-user-domain-id default \
          --os-project-name demo \
          --os-username demo --os-password {{ demo_password }} \
          router-create demo-router
      when: router_list.stdout.find('demo-router') == -1
    - name: Attach the router to the demo tenant subnet
      command: >
        neutron \
          --os-auth-url http://controller:35357/v3 \
          --os-project-domain-id default --os-user-domain-id default \
          --os-project-name demo \
          --os-username demo --os-password {{ demo_password }} \
          router-interface-add demo-router demo-subnet
      ignore_errors: yes
    - name: Attach the router to the external network by setting it as the gateway
      command: >
        neutron \
          --os-auth-url http://controller:35357/v3 \
          --os-project-domain-id default --os-user-domain-id default \
          --os-project-name demo \
          --os-username demo --os-password {{ demo_password }} \
          router-gateway-set demo-router ext-net
